Describe the api for working with the database
ToltekPlus/lamoda pull request #51
Opened 2023-04-29 08:58 UTC by sergeybulankin

2023-04-29 11:00 UTC, GaynetdinovR reviewed
Не поднимается nginx. Ошибка: "add_header" directive is not allowed here in 
/etc/nginx/conf.d/default.conf:7

2023-05-03 15:54 UTC, DaNiK2 requested changes
На unix системах сам docker запускается нормально, но при запуске lint жалуется на строчку 15 в файле CartComponent.vue

https://github.com/ToltekPlus/lamoda/blob/43ae456dde87751713cd6bce96bc070e4331d6c5/nodejs/src/components/Header/components/Cart/CartComponent.vue#L15

**Ошибка:** error This 'v-if' should be moved to the wrapper element vue/no-use-v-if-with-v-for

2023-05-03 15:54 UTC, DaNiK2 commented on nodejs/src/components/Header/components/Cart/CartComponent.vue
> +              <td v-for="(item, i) in list" :key="i" v-if="list !== null">
Lint жалуется на эту строчку

 **error  This 'v-if' should be moved to the wrapper element  vue/no-use-v-if-with-v-for**

@sergeybulankin

2023-05-06 08:41 UTC, sergeybulankin commented on nodejs/src/components/Header/components/Cart/CartComponent.vue
> +              <td v-for="(item, i) in list" :key="i" v-if="list !== null">
исправлено

2023-05-06 08:42 UTC, sergeybulankin commented
Добавлены изменения для пользователей windows
Теперь адрес для фронта localhost:4000

2023-05-06 11:59 UTC, GaynetdinovR approved these changes
Работает

2023-05-13 05:24 UTC, DaNiK2 approved these changes
На Unix системах работает

2023-05-13 05:49 UTC, micromaxd303 approved these changes
👍

2023-05-18 20:05 UTC, merged